AWSTemplateFormatVersion: '2010-09-09'
Description: "SUU Project - Domain Stack"

Parameters:
  DomainName:
    Type: String
    Default: "mnessel.pl"

Resources:
 Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Join [ "", ["*.", !Ref DomainName] ]
      ValidationMethod: DNS
