AWSTemplateFormatVersion: '2010-09-09'
Description: "SUU Project - Domain Stack"

Parameters:
  DomainName:
    Type: String
    Default: "mnessel.pl"

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - "*." !Ref DomainName
      ValidationMethod: DNS

  ApiCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref DomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref Certificate

